# Generated by Django 5.2 on 2025-04-14 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.category'),
        ),
        migrations.CreateModel(
            name='ReportPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(1, 'Monthly'), (2, 'Bi-Monthly'), (3, 'Quarterly'), (4, 'Third-Yearly'), (6, 'Semi-Annually'), (12, 'Annually')], default=1)),
                ('is_enabled', models.BooleanField(default=False)),
                ('include_insights', models.BooleanField(default=True)),
                ('include_category_distribution', models.BooleanField(default=True)),
                ('include_spending_trends', models.BooleanField(default=True)),
                ('include_monthly_summary', models.BooleanField(default=True)),
                ('last_report_date', models.DateTimeField(blank=True, null=True)),
                ('next_report_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Category',
                'verbose_name_plural': 'User Categories',
                'unique_together': {('user', 'category')},
            },
        ),
    ]
