# Generated by Django 5.2 on 2025-04-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminsettings_adminbulkemail_requestlog'),
    ]

    operations = [
    ]
