# Generated by Django 5.2 on 2025-04-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fix_transaction_category_data'),
    ]

    operations = [
    ]
