export const GlobalContextInitialValues = {
  isUnlocked: false,
  appInactive: false,
  isAuthenticated: false,
  authenticate: async () => {},
  setIsUnlocked: () => {},
  session: null,
  User: null,
  setUser: () => {},
  loading: false,
  isLockPinSet: false,
  setIsLockPinSet: () => {},
  setLockPin: () => {},
  UserCurrency: 'USD',
  getUserCurrency: async () => {},
  isBiometricSupported: false,
  isBiometricEnabled: false,
};

export const DataProviderInitialValues = {
  transactionsData: [],
  isLoading: false,
  fetchTransactions: async () => {},
  deleteTransaction: async () => {},
  addTransaction: async () => {},
  updateTransaction: async () => {},
  categoriesData: [],
  fetchCategories: async () => {},
  addCategory: async () => {},
  updateCategory: async () => {},
  deleteCategory: async () => {},
  uploadImage: async () => {},
  deleteImage: async () => {},
  uploadFile: async () => {},
  deleteFile: async () => {},
};
