# Generated by Django 5.2 on 2025-04-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiAuth', '0002_user_account_status_user_loginattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
